I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 244, in script
    jump mackback1
ScriptError: could not find label 'mackback1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 244, in script
    jump mackback1
  File "/Users/sam/renpy-8.0.3-sdk/renpy/ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/sam/renpy-8.0.3-sdk/renpy/script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'mackback1'.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
Careful Watchers 1.0
Mon Oct 17 00:25:07 2022
